group 'com.aiflow.mathink'
version '0.1.0'

buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:8.1.0' }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.aiflow.mathink'
    compileSdkVersion 34

    defaultConfig { minSdkVersion 24 }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.0'
}
